[package]
name = "gigasecond"
version = "0.1.0"
authors = ["Jeremy Miller <jgmiller88@gmail.com>"]

[dependencies]

[dev-dependencies]
cargo-outdated = "0.7.0"
cargo-testify = "0.2.0"
cargo-tarpaulin = "0.5.6"
